server:
  port: 8091
spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  output:
    ansi:
      enabled: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/app_2023?useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    root: info
    org.hibernate.type.descriptor.sql: trace
custom:
  site:
    name: MUT
    baseUrl: "http://localhost:8091"
